name: Doodle Sync FE deployment pipeline
run-name: ${{github.actor}} is currently deploying doodle Sync
on: [push, workflow_dispatch]
jobs: 
  run-tests:
  runs-on: ubuntu-latest
  steps:
    - name: download project
      uses: action/checkout@v3
    - name: install node version 18
      uses: actions/setup-node@v3.8.1
    - name: install yarn
      uses: mskelton/setup-yarn@v1.4.0
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: run tests
      run: yarn test
  uploads-artifacts:
  runs-on: ubuntu-latest
  needs: [run-tests]
  steps:
    - name: download project
      uses: actions/checkout@v3
    - name: install node version 18
      uses: actions/setup-node@v3.8.1
    - name: install yarn
      uses: mskelton/setup-yarn@v1.4.0
    - name: install dependencies
      run: yarn install --frozen-lockfile
    - name: build project
      run: yarn build
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: doodle-sync-fe
        path: dist
